name: Markdown lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo gem install mdl
    - name: Markdown lint
      run: |
        mdl README.md
